name: Submit your Microsoft Fabric FabCon Global Hackathon Project. You may submit more than one project, but each submission must be unique and substantially different from your other entries.
description: "Submit your project any time before November 3rd, 11:59 PM PST."
title: "Project Name"
body:
  - type: input
    id: rep-name
    attributes:
      label: First and Last Name
      description: Please use the same name you used to register at https://aka.ms/FabConRegister
    validations:
      required: true

  - type: dropdown
    id: learn-completion
    attributes:
      label: MS Learn Fabric Skilling Plan Completion 
      description: Did you complete the Skilling Plan?
      options:
        - 'Selection'
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Project Pitch or Description
      description: Provide a short elevator pitch for your project including what you built, which Microsoft and Azure technologies used, what it does, what problem it solves. 
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Project Repository URL
      description: Share a URL to your GitHub code repository. If the repository is private, grant read access to the GitHub users @toolboc and @jcardif before submitting.
    validations:
      required: true

  - type: input
    id: video
    attributes:
      label: Project Demo video URL
      description: Share the link to a 3–5-minute public video to YouTube, Vimeo, Facebook, or Youku demonstrating your project in action.  
    validations:
      required: true

  - type: input
    id: teammembers
    attributes:
      label: Team members
      description: Comma-separated list of GitHub usernames who also worked on this project. 
    validations:
      required: false

  - type: checkboxes
    id: registered
    attributes:
      label: Registration status.
      description: By submitting this project, you confirm that your team is registered for the hackathon. Only registered teams will be considered. To register, complete the form at [aka.ms/FabConHackRegister](https://aka.ms/FabConHackRegister)
      options:
        - label: I have completed registration
          required: true